### ISSUE TITLE
Not able to build on kernel 5.15.136-tegra

### ISSUE THREAD

**Issue by ninoweg** [paroj/xpad#308]
I tried to install xpad
```
sudo git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
sudo dkms install -m xpad -v 0.4
```
Which threw the following error
```
Creating symlink /var/lib/dkms/xpad/0.4/source -> /usr/src/xpad-0.4

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.15.136-tegra KVERSION=5.15.136-tegra...(bad exit status: 2)
ERROR (dkms apport): binary package for xpad: 0.4 not found
Error! Bad return status for module build on kernel: 5.15.136-tegra (aarch64)
Consult /var/lib/dkms/xpad/0.4/build/make.log for more information.
```

So i ran 
```
cd /usr/src/xpad-0.4
sudo make
```

Again resulting in another error message
```
make -C /lib/modules/5.15.136-tegra/build V=1 M= modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.136-tegra-ubuntu22.04_aarch64/3rdparty/canonical/linux-jammy/kernel-source'
make -f ./scripts/Makefile.build obj=scripts/basic
make -f ./scripts/Makefile.build obj=scripts/dtc
make -f ./scripts/Makefile.build obj=scripts
make -f ./scripts/Makefile.build obj=scripts/genksyms \
 \
need-builtin= \
need-modorder=
make -f ./scripts/Makefile.build obj=scripts/selinux \
 \
need-builtin= \
need-modorder=
make -f ./scripts/Makefile.build obj=scripts/selinux/genheaders \
 \
need-builtin= \
need-modorder=
make -f ./scripts/Makefile.build obj=scripts/selinux/mdp \
 \
need-builtin= \
need-modorder=
  gcc -Wp,-MMD,scripts/.sorttable.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89      -I./tools/include   -o scripts/sorttable scripts/sorttable.c   
scripts/sorttable.c:34:10: fatal error: tools/be_byteshift.h: No such file or directory
   34 | #include <tools/be_byteshift.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.host:95: scripts/sorttable] Error 1
make[1]: *** [Makefile:1250: scripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.136-tegra-ubuntu22.04_aarch64/3rdparty/canonical/linux-jammy/kernel-source'
make: *** [Makefile:5: all] Error 2
```

I would appreciate some help on how to resolve this issue.

**Comment by paroj** [comment]
should be working now
