### ISSUE TITLE
Fail to intall dkms kernel 6.16

### ISSUE THREAD

**Issue by LordDarkfat** [paroj/xpad#331]
Hi,
I get the following errors when trying to install DKMS with Kernel 6.16.

```
Deprecated feature: CLEAN (/usr/src/xpad-0.4/dkms.conf)
Creating symlink /var/lib/dkms/xpad/0.4/source -> /usr/src/xpad-0.4

Sign command: /usr/lib/modules/6.16.0-3-MANJARO/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j32 KERNELRELEASE=6.16.0-3-MANJARO KVERSION=6.16.0-3-MANJARO

Error! Bad return status for module build on kernel: 6.16.0-3-MANJARO (x86_64)
Consult /var/lib/dkms/xpad/0.4/build/make.log for more information.
```

Make.log shows this,

`xpad.c:851:33: error: implicit function declaration  ‘from_timer’`

`xpad.c:851:53: error: ‘ghl_poke_timer’`

**Comment by paroj** [comment]
should be fixed with 9caad15ba366c26337bfbcf3ee1144a6cc07d9ca
